name: Build and Publish

on:
  push:
    branches:
      - master
  watch:
    types: [started]

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production

    if: github.actor == github.event.repository.owner.login

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: NPM Install
        run: npm ci
      - name: NPM test and build
        run: |
          npm test
          npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with: 
          name: public
          path: public/


  deploy:
    name: Deploy build to production
    runs-on: ubuntu-latest
    needs: build
    if: github.actor == github.event.repository.owner.login
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@master
        with:
          name: public
          path: public/
      - name: Zip files for upload
        run: |
          mkdir ${GITHUB_SHA}
          mv public ${GITHUB_SHA}
          date > ${GITHUB_SHA}/buildInfo
          zip -r ${GITHUB_SHA}.zip ${GITHUB_SHA}
      - name: Create Key file
        run: echo -e "${IDRSAPUB}" > KEY_FILE && chmod 600 KEY_FILE && ls -l
      - name: SCP files to server
        run: scp -v -i KEY_FILE -o StrictHostKeyChecking=no ${GITHUB_SHA}.zip ${SCP_USER_AT_HOST}:~/github-actions/